# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Ridong Zhang"
title_separator          : "-"
name                     : &name "Ridong Zhang"
description              : &description "Research on Interpretability and Reliability of Large Language Models"

url                      : "https://euaroto.github.io"
baseurl                  : "/ridongz.github.io"
repository               : "euaroto/ridongz.github.io"
